class ParamsKeys:
    URL = "url"
    URL_LENGTH = "length_url"
    EMAIL_IN_URL = "email_in_url"
    EMAIL_IN_HOSTNAME = "email_in_hostname"
    EMAIL_IN_PATH = "email_in_path"
    IS_SHORTENED_URL = "is_shortened_url"
    STATUS = "status"
    DATASET_NAME = "shashwatwork/web-page-phishing-detection-dataset"
    ZIP_FILE_NAME = "web_page_phishing_detection.zip"
    CSV_FILE_NAME = "dataset_phishing.csv"
    EXTRACTED_FOLDER_NAME = "extracted"
    HOSTNAME_LENGTH = "length_hostname"
    PATH_LENGTH = "path_length"
    QUERY_LENGTH = "query_length"
    SPECIAL_CHAR_COUNT = "special_char_count"